#!/usr/bin/env python
# -*- coding: utf-8 -*-
encoding = 'utf-8'

import os, sys
import lib.functions as functions

#check for dependencies
functions.depcheck()

#start GUI
os.system("python lib/main.py")
